version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - github-packages

registries:
  github-packages:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/ValentynaBondarenko/datasource-listener"
    username: "${{ secrets.ARTIFACTORY_USERNAME }}"
    password: "${{ secrets.ARTIFACTORY_PASSWORD }}"


