spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:8200/movieland?characterEncoding=UTF-8
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    clear-checksums: false
  jpa:
    show-sql: true
    open-in-view: false

logging:
  config: classpath:logback.xml
  level:
    liquibase: debug

movieland:
  movie:
    random:
      limit: 3
  genre:
    cache:
      update:
        interval: ${GENRE_CACHE_UPDATE:14400000}
