openapi: 3.0.3
info:
  version: 0.0.1
  title: MovieLand
  description: "<p>This service for searching and discovering movies. <p>
    Users can find films of different genres, ratings, and more. They can also rate movies and leave comments. <p>"

servers:
  - url: /api/v1

components:
  schemas:
    MovieResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nameUkrainian:
          type: string
        nameNative:
          type: string
        yearOfRelease:
          type: integer
          format: int32
        description:
          type: string
        rating:
          type: number
          format: double
        price:
          type: number
          format: double
        poster:
          type: string

    GenreResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique genre identifier
        name:
          type: string
          description: Genre name

    CountryResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique countrie identifier
        name:
          type: string
          description: Countries name

    MovieSortRequest:
      type: object
      properties:
        ratingDirection:
          type: string
          description: Sort direction for rating (optional).
          enum: [ "ASC", "DESC" ]
        priceDirection:
          type: string
          description: Sort direction for price (optional).
          enum: [ "ASC", "DESC" ]

    MovieRequest:
      type: object
      properties:
        nameUkrainian:
          type: string
          description: The Ukranian name of the movie
        nameNative:
          type: string
          description: The original name of the movie
        yearOfRelease:
          type: integer
          description: The year the movie was released
        description:
          type: string
          description: Description of the movie
        price:
          type: number
          format: double
          description: Price of the movie
        rating:
          type: number
          format: double
          description: Rating of the movie
        picturePath:
          type: string
          description: URL to the movie's picture
        countries:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/CountryResponse'
          description: Set of countries (only genre names)
        genres:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/GenreResponse'
          description: Set of genres (only genre names)

    FullMovieResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nameUkrainian:
          type: string
        nameNative:
          type: string
        yearOfRelease:
          type: integer
          format: int32
        description:
          type: string
        rating:
          type: number
          format: double
        price:
          type: number
          format: double
        picturePath:
          type: string
        genres:
          type: array
          items:
            $ref: '#/components/schemas/GenreResponse'
        countries:
          type: array
          items:
            $ref: '#/components/schemas/CountryResponse'
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/ReviewResponse'

    ReviewResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique review identifier
        user:
          $ref: '#/components/schemas/UserIdResponse'
        text:
          type: string
          description: Review text

    UserRequest:
      type: object
      description: >
        Request object for user authentication. Contains the user's email and password,
        which must be validated for correctness and non-emptiness.
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: User's password
          minLength: 8

    UserUUIDResponse:
      type: object
      description: Response object for successful authentication.
      properties:
        uuid:
          type: string
          format: uuid
          description: Unique user identifier
          example: e5e84a87-2732-422e-8b1a-bd61ad7ec399
        nickname:
          type: string
          description: User's nickname
          example: Jane Doe

    UserIdResponse:
      type: object
      description: Response user.
      properties:
        id:
          type: integer
          format: int64
          description: Unique user identifier
          example: 1
        nickname:
          type: string
          description: User's nickname
          example: Jane Doe

    ProblemDetails:
      required:
        - detail
        - status
      type: object
      properties:
        type:
          description: |
            A URI reference according to IETF RFC 3986 [5] that identifies the problem type.
            It is encouraged that the URI provides human-readable documentation for the problem (e.g. using HTML) when dereferenced.
            When this member is not present, its value is assumed to be "about:blank".
          type: string
        title:
          type: string
          description: |
            A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem,
            except for purposes of localization. If type is given and other then "about:blank", this attribute shall also be provided.
            A short, human-readable summary of the problem type.  It SHOULD NOT change from occurrence to occurrence of the problem,
            except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4).
        status:
          type: integer
          description: |
            The HTTP status code for this occurrence of the problem. The HTTP status code ([RFC7231], Section 6) generated by the origin
            server for this occurrence of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem. It may yield further information if dereferenced.
      description: |
        The definition of the general "ProblemDetails" data structure from IETF RFC 7807 [19] is reproduced in this structure.
        Compared to the general framework defined in IETF RFC 7807 [19], the "status" and "detail" attributes are mandated to be included
        by the present document, to ensure that the response contains additional textual information about an error. IETF RFC 7807 [19]
        foresees extensibility of the "ProblemDetails" type. It is possible that particular APIs in the present document, or particular
        implementations, define extensions to define additional attributes that provide more information about the error. The description
        column only provides some explanation of the meaning to Facilitate understanding of the design. For a full description,
        see IETF RFC 7807 [19].

  responses:
    BadRequest:
      description: |
        Bad Request If the request is malformed or syntactically incorrect (e.g. if the request URI contains incorrect query parameters or
        the payload body contains a syntactically incorrect data structure), the API producer shall respond with this response code. --- If the
        response to a GET request which queries a container resource would be so big that the performance of the API producer is adversely affected,
        and the API producer does not support paging for the affected resource, it shall respond with this response code. --- If there is an
        application error related to the client's input that cannot be easily mapped to any other HTTP response code ("catch all error"), the API
        producer shall respond with this response code.
      headers:
        Content-Type:
          description: The MIME type of the body of the response.
          schema:
            type: string
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    BasicOk:
      description: |
        OK.

        The request has succeeded.
      headers:
        Content-Type:
          description: The MIME type of the body of the response.
          schema:
            type: string
      content: { }

    Forbidden:
      description: |
        Forbidden If the API consumer is not allowed to perform a particular request to a particular resource, the API producer shall respond
        with this response code. The "ProblemDetails" structure shall be provided.  It should include in the "detail" attribute information about
        the source of the problem, and may indicate how to solve it.
      headers:
        Content-Type:
          description: The MIME type of the body of the response.
          schema:
            type: string
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    NotFound:
      description: |
        Not Found If the API producer did not find a current representation for the resource addressed by the URI passed in the request, or is not
        willing to disclose that one exists, it shall respond with this response code.  The "ProblemDetails" structure may be provided, including
        in the "detail" attribute information about the source of the problem, e.g. a wrong resource URI variable.
      headers:
        Content-Type:
          description: The MIME type of the body of the response.
          schema:
            type: string
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Unauthorized:
      description: |
        Unauthorized If the request contains no access token even though one is required, or if the request contains an authorization token that
        is invalid (e.g. expired or revoked), the API producer should respond with this response. The details of the error shall be returned in
        the WWW-Authenticate HTTP header, as defined in IETF RFC 6750 and IETF RFC 7235. The ProblemDetails structure may be provided.
      headers:
        Content-Type:
          description: The MIME type of the body of the response.
          schema:
            type: string
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ProblemDetails'

paths:
  '/movies':
    get:
      description: |
        Get all movies with optional sorting by rating and price.
        
        The GET method finds all movies. You can optionally sort the results by rating (desc) or price (asc/desc).
      summary: Get all movies
      operationId: findAllMovies
      tags:
        - Movie
      parameters:
        - name: MovieSortRequest
          in: query
          description: Sort criteria for movies (optional).
          schema:
            $ref: '#/components/schemas/MovieSortRequest'
          required: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieResponse'

        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      description: |
        Add new movie
        
        The POST method add movie
        tags:
        - Movie
      summary: Add new movie
      operationId: addMovie
      tags:
        - Movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieRequest'
      responses:
        '201':
          description: Movie successfully created
          content: { }
        '400':
          $ref: '#/components/responses/BadRequest'

  '/movies/random':
    get:
      description: |
        Get randome movies .

        The GET method find couple ramdome movies.
      summary: Get random movies
      operationId: getRandomMovies
      tags:
        - Movie
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  '/movies/genres/{genreId}':
    get:
      description: |
        Get movies by genre.

        The GET method find move by genre.
      summary: Get movies by genre
      operationId: getMoviesByGenre
      tags:
        - Movie
      parameters:
        - name: genreId
          in: path
          required: true
          description: ID of the genre
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  '/movies/{id}':
    get:
      description: |
        Get movie by id.

        The GET method finds one movie by id.
      summary: Get movie
      operationId: getMovieById
      tags:
        - Movie
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the movie
          schema:
            type: integer
            format: int64
        - name: currency
          in: query
          required: false
          description: Currency for calculating the price of the movie. Specify the currency code (e.g., USD, EUR) to retrieve the movie price in the selected currency. If not specified, the price will be returned in the default currency (UAH).
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullMovieResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Edit existing movie
      description: Edit movie by ID
      operationId: editMovie
      tags:
        - Movie
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the movie to edit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieRequest'
      responses:
        '200':
          description: Movie successfully updated
        '400':
          description: Invalid input
        '404':
          description: Movie not found

  '/genres':
    get:
      description: |
        Get all genres.

        The GET method finds all genres.
      operationId: findAllGenres
      tags:
        - Genre
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/GenreResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  '/login':
    post:
      summary: User login
      description: |
        Authenticate user and generate token.

        The POST method validates user credentials and returns a token.
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
            example:
              email: "jane.doe@example.com"
              password: "password"
      responses:
        '200':
          description: Successful login, returns token and nickname
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUUIDResponse'
              example:
                uuid: "e5e84a87-2732-422e-8b1a-bd61ad7ec399"
                nickname: "Jane Doe"
        '400':
          $ref: '#/components/responses/BadRequest'

  '/logout':
    delete:
      description: |
        Logout user by invalidating the token.

        The DELETE method requires a valid token in the header.
      summary: User logout
      operationId: logoutUser
      tags:
        - Auth
      parameters:
        - in: header
          name: uuid
          required: true
          schema:
            type: string
            format: uuid
          description: Token to invalidate (logout)
      responses:
        '204':
          description: Successful logout
        '400':
          $ref: '#/components/responses/BadRequest'