ALTER SEQUENCE users_id_seq INCREMENT BY 50;
ALTER SEQUENCE movies_id_seq INCREMENT BY 50;
ALTER SEQUENCE genres_id_seq INCREMENT BY 50;
ALTER SEQUENCE countries_id_seq INCREMENT BY 50;
ALTER SEQUENCE reviews_id_seq INCREMENT BY 50;