name: Enable auto-merge for Dependabot

on:
  pull_request:
    types:
      - opened

jobs:
  enable-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.graphql(`
              mutation {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: "${{ github.event.pull_request.node_id }}",
                  mergeMethod: MERGE
                }) {
                  pullRequest {
                    number
                    autoMergeRequest {
                      enabledAt
                    }
                  }
                }
              }
            `)
