name: Generate Javadoc

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate-and-commit-javadoc:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "github-bondarenko-packages",
                "username": "${{ env.ARTIFACTORY_USERNAME }}",
                "password": "${{ env.ARTIFACTORY_PASSWORD }}"
            }]

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Check Javadoc
        run: |
          mkdir -p docs
          cd docs
          ls

      - name: Copy Javadoc to docs directory
        run: |
          cp -r ./target/site/apidocs/* docs/
          cd docs
          ls

      - name: Commit Javadoc to Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add docs
          git commit -m 'Update Javadoc documentation'
          git push origin HEAD:main
