name: Movieland CI
on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '23'
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      MOVIELAND_TOKEN_SECRET: ${{ secrets.MOVIELAND_TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 23
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -Dspring.profiles.active=test

      - name: SonarCloud Scan
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn sonar:sonar \
                      -Dsonar.projectKey=ValentynaBondarenko_Movieland-Pro \
                      -Dsonar.organization=valentynabondarenko \
                      -Dsonar.host.url=https://sonarcloud.io \
                      -Dsonar.login=${{ env.SONAR_TOKEN }} \
                      -Dsonar.exclusions=**/*.java
