name: Movieland CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "github-bondarenko-packages",
                "username": "${{ env.ARTIFACTORY_USERNAME }}",
                "password": "${{ env.ARTIFACTORY_PASSWORD }}"
            }]

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=ValentynaBondarenko_Movieland-Pro \
          -Dsonar.organization=valentynabondarenko \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ env.SONAR_TOKEN }} \
          -Dsonar.exclusions=**/*.java