name: Movieland CI
on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '21'
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{
          "id": "github-bondarenko-packages", 
          "username": "${{ secrets.ARTIFACTORY_USERNAME }}",
          "password": "${{ secrets.ARTIFACTORY_PASSWORD }}"
          }]'

      - name: Build with Maven
        run: mvn clean package

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
                      -Dsonar.projectKey=ValentynaBondarenko_Movieland-Pro \
                      -Dsonar.organization=valentynabondarenko \
                      -Dsonar.host.url=https://sonarcloud.io \
                      -Dsonar.login=${{ env.SONAR_TOKEN }} \
                      -Dsonar.exclusions=**/*.java
